import type { Product } from '@/types';

export const mockClothingProducts: Product[] = [
  {
    id: 1,
    title: "Синій джинсовий светр",
    price: 45.99,
    description: "Зручний джинсовий светр для повсякденного носіння",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    rating: { rate: 4.3, count: 120 },
    size: "M",
    color: "Blue",
    inStock: true,
    brand: "Denim Co",
    material: "Denim"
  },
  {
    id: 2,
    title: "Червона сукня",
    price: 120.00,
    description: "Елегантна вечірня сукня",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    rating: { rate: 4.7, count: 85 },
    size: "S",
    color: "Red",
    inStock: true,
    brand: "Elegance",
    material: "Silk"
  },
  {
    id: 3,
    title: "Зелені шорти",
    price: 35.50,
    description: "Літні шорти для активного відпочинку",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    rating: { rate: 4.1, count: 200 },
    size: "L",
    color: "Green",
    inStock: true,
    brand: "Outdoor",
    material: "Cotton"
  },
  {
    id: 4,
    title: "Біла блузка",
    price: 29.99,
    description: "Класична блузка для офісу",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    rating: { rate: 4.0, count: 95 },
    size: "M",
    color: "White",
    inStock: false,
    brand: "OfficeStyle",
    material: "Polyester"
  },
  {
    id: 5,
    title: "Чорна куртка",
    price: 89.99,
    description: "Тепла зимова куртка",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    rating: { rate: 4.5, count: 150 },
    size: "XL",
    color: "Black",
    inStock: true,
    brand: "WinterGear",
    material: "Polyester"
  },
  {
    id: 6,
    title: "Рожева спідниця",
    price: 42.75,
    description: "Модна спідниця для весняного сезону",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    rating: { rate: 4.2, count: 65 },
    size: "XS",
    color: "Pink",
    inStock: true,
    brand: "FashionWeek",
    material: "Wool"
  },
  {
    id: 7,
    title: "Сірий светр",
    price: 55.00,
    description: "Теплий светр для холодної погоди",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    rating: { rate: 4.4, count: 180 },
    size: "L",
    color: "Gray",
    inStock: true,
    brand: "CozyWear",
    material: "Wool"
  },
  {
    id: 8,
    title: "Жовта футболка",
    price: 19.99,
    description: "Яскрава футболка для літа",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    rating: { rate: 3.9, count: 110 },
    size: "M",
    color: "Yellow",
    inStock: true,
    brand: "SummerFun",
    material: "Cotton"
  }
];
