import type { Product } from '@/types';

export const mockClothingProducts: Product[] = [
  {
    id: 1,
    title: "Синій джинсовый светр",
    price: 45.99,
    description: "Зручний джинсовий светр для повсякденного носіння",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    rating: { rate: 4.3, count: 120 },
    size: "M",
    color: "Blue",
    inStock: true,
    brand: "Denim Co",
    material: "Denim"
  },
  {
    id: 2,
    title: "Червона сукня",
    price: 120.00,
    description: "Елегантна вечірня сукня",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop",
    rating: { rate: 4.7, count: 85 },
    size: "S",
    color: "Red",
    inStock: true,
    brand: "Elegance",
    material: "Silk"
  },
  {
    id: 3,
    title: "Зелені шорти",
    price: 35.50,
    description: "Літні шорти для активного відпочинку",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1506629905607-e48b0e67d879?w=400&h=400&fit=crop",
    rating: { rate: 4.1, count: 200 },
    size: "L",
    color: "Green",
    inStock: true,
    brand: "Outdoor",
    material: "Cotton"
  },
  {
    id: 4,
    title: "Біла блузка",
    price: 29.99,
    description: "Класична блузка для офісу",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=400&h=400&fit=crop",
    rating: { rate: 4.0, count: 95 },
    size: "M",
    color: "White",
    inStock: false,
    brand: "OfficeStyle",
    material: "Polyester"
  },
  {
    id: 5,
    title: "Чорна куртка",
    price: 89.99,
    description: "Тепла зимова куртка",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop",
    rating: { rate: 4.5, count: 150 },
    size: "XL",
    color: "Black",
    inStock: true,
    brand: "WinterGear",
    material: "Polyester"
  },
  {
    id: 6,
    title: "Рожева спідниця",
    price: 42.75,
    description: "Модна спідниця для весняного сезону",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&h=400&fit=crop",
    rating: { rate: 4.2, count: 65 },
    size: "XS",
    color: "Pink",
    inStock: true,
    brand: "FashionWeek",
    material: "Wool"
  },
  {
    id: 7,
    title: "Сірий светр",
    price: 55.00,
    description: "Теплий светр для холодної погоди",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=400&fit=crop",
    rating: { rate: 4.4, count: 180 },
    size: "L",
    color: "Gray",
    inStock: true,
    brand: "CozyWear",
    material: "Wool"
  },
  {
    id: 8,
    title: "Жовта футболка",
    price: 19.99,
    description: "Яскрава футболка для літа",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    rating: { rate: 3.9, count: 110 },
    size: "M",
    color: "Yellow",
    inStock: true,
    brand: "SummerFun",
    material: "Cotton"
  },
  {
    id: 9,
    title: "Коричневі штани",
    price: 65.00,
    description: "Стильні штани для будь-якого випадку",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop",
    rating: { rate: 4.6, count: 95 },
    size: "M",
    color: "Brown",
    inStock: true,
    brand: "UrbanStyle",
    material: "Cotton"
  },
  {
    id: 10,
    title: "Блакитна сукня",
    price: 75.50,
    description: "Легка літня сукня",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&h=400&fit=crop",
    rating: { rate: 4.3, count: 120 },
    size: "S",
    color: "Light Blue",
    inStock: true,
    brand: "SummerBreeze",
    material: "Linen"
  },
  {
    id: 11,
    title: "Чорна футболка",
    price: 24.99,
    description: "Базова чорна футболка",
    category: "men's clothing",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    rating: { rate: 4.0, count: 200 },
    size: "L",
    color: "Black",
    inStock: true,
    brand: "BasicWear",
    material: "Cotton"
  },
  {
    id: 12,
    title: "Зелена блузка",
    price: 39.99,
    description: "Яскрава весняна блузка",
    category: "women's clothing",
    image: "https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=400&h=400&fit=crop",
    rating: { rate: 4.1, count: 85 },
    size: "M",
    color: "Green",
    inStock: true,
    brand: "SpringStyle",
    material: "Silk"
  }
];
