import type { Product } from '@/types';

export const mockClothingProducts: Product[] = [
  {
    id: 1,
    title: "Блуза 'Зефір'",
    price: 89.99,
    description: "Отримайте неперевершений вечірній образ із блузою 'Зефір', що вражає своєю прозорою, повітряною сітчастою тканиною та драматичними рукавами-буфами. Ефектний бант на високій горловині додає виробу вишуканої грайливості та елегантності.",
    category: "women's clothing",
    image: "https://i.pinimg.com/1200x/54/a8/97/54a8971019ab6dcd99fe18f7da6c864f.jpg",
    rating: { rate: 4.8, count: 24 },
    size: "M",
    color: "Білий",
    inStock: true,
    brand: "LINO",
    material: "Сітчаста тканина, шифон"
  },
  {
    id: 2,
    title: "Сукня 'Німфа'",
    price: 159.99,
    description: "Казковий та романтичний образ, що поєднує вишукану текстуру та повітряний силует. Ніжний молочний колір, тривимірна квіткова аплікація та акцентні рукави-ліхтарики створюють незабутній дизайн.",
    category: "women's clothing",
    image: "https://i.pinimg.com/736x/5d/30/fd/5d30fde06e55ed9411a3b2aedb5c1df6.jpg",
    rating: { rate: 4.9, count: 18 },
    size: "S",
    color: "Молочний",
    inStock: true,
    brand: "LINO",
    material: "Шифон, мереживо"
  },
  {
    id: 3,
    title: "Сукня 'Камея'",
    price: 139.99,
    description: "Романтичний та архітектурний виріб у ніжно-рожевому відтінку, що переосмислює вікторіанський стиль. Корсетний ліф із V-подібним вирізом, прикрашений витонченою вишивкою, ідеально моделює талію.",
    category: "women's clothing",
    image: "https://i.pinimg.com/originals/84/62/ad/8462ad1794436c6144f9cad76b1b84fa.png",
    rating: { rate: 4.7, count: 32 },
    size: "L",
    color: "Рожевий",
    inStock: false,
    brand: "LINO",
    material: "Сатен, вишивка"
  },
  {
    id: 4,
    title: "Жакет 'Болеро Барокко'",
    price: 79.99,
    description: "Укорочений кроп-жакет, що миттєво перетворює будь-який образ на подіумний, поєднуючи класику та драму. Виріб виконаний із розкішної жакардової тканини зі світло-бежевим візерунком.",
    category: "women's clothing",
    image: "https://i.pinimg.com/1200x/6e/93/63/6e936397b36a5219276b35012e830344.jpg",
    rating: { rate: 4.5, count: 15 },
    size: "M",
    color: "Бежевий",
    inStock: true,
    brand: "LINO",
    material: "Жакардова тканина"
  },
  {
    id: 5,
    title: "Спідниця 'Скайлайн'",
    price: 99.99,
    description: "Архітектурний шедевр, що поєднує строгість та грайливість. Вона має унікальну двошарову конструкцію: верхній шар із фігурним подолом та вертикальною строчкою, що візуально витягує силует.",
    category: "women's clothing",
    image: "https://i.pinimg.com/1200x/be/38/ef/be38eff8e211ee0796f7b8e4c2a6d1cb.jpg",
    rating: { rate: 4.6, count: 21 },
    size: "XS",
    color: "Чорний",
    inStock: true,
    brand: "LINO",
    material: "Креп, шовк"
  },
  {
    id: 6,
    title: "Штани 'Фламенко'",
    price: 119.99,
    description: "Драматичний та елегантний виріб, що поєднує класичний чорний колір із неймовірним акцентом на подолі. Висока посадка та чіткі вертикальні шви спереду візуально подовжують силует.",
    category: "women's clothing",
    image: "https://i.pinimg.com/736x/d5/7f/6d/d57f6d3b806155898c4228b682ece92f.jpg",
    rating: { rate: 4.4, count: 28 },
    size: "M",
    color: "Чорний",
    inStock: false,
    brand: "LINO",
    material: "Креп, органза"
  },
  {
    id: 7,
    title: "Світшот 'Урбан'",
    price: 49.99,
    description: "Базова модель для повсякденного комфорту, виконана в універсальному темно-сірому кольорі. Виріб має вільний, не обмежуючий рухів крій (оверсайз), що ідеально підходить для створення багатошарових образів.",
    category: "men's clothing",
    image: "https://i.pinimg.com/736x/76/e0/b9/76e0b9620e33e6b1d1b8ed7878a03b40.jpg",
    rating: { rate: 4.3, count: 45 },
    size: "L",
    color: "Темно-сірий",
    inStock: true,
    brand: "LINO",
    material: "Бавільна, трикотаж"
  },
  {
    id: 8,
    title: "Худі 'Вічна Ніч'",
    price: 69.99,
    description: "Преміальна модель оверсайз, що вирізняється ефектом 'вивареної' тканини та глибоким, зістареним чорним кольором. Незвичайний крій із об'ємними рукавами та фігурними накладними кишенями на грудях.",
    category: "men's clothing",
    image: "https://i.pinimg.com/736x/57/95/4b/57954bdef49acdd360e1aafafe5c2a7c.jpg",
    rating: { rate: 4.7, count: 38 },
    size: "XL",
    color: "Чорний",
    inStock: true,
    brand: "LINO",
    material: "Бавільна, зістаренна тканина"
  },
  {
    id: 9,
    title: "Джинси 'Ретро-Кежуал'",
    price: 89.99,
    description: "Актуальна модель із вільним, прямим кроєм, що забезпечує максимальний комфорт і свободу рухів. Світлий, виварений денім із вінтажним ефектом ідеально вписується в будь-який повсякденний образ.",
    category: "men's clothing",
    image: "https://i.pinimg.com/736x/5f/70/9d/5f709d100d36ae44aa714851cd1cb58e.jpg",
    rating: { rate: 4.5, count: 52 },
    size: "M",
    color: "Світло-синій",
    inStock: true,
    brand: "LINO",
    material: "Денім бавовняний"
  },
  {
    id: 10,
    title: "Пуховик 'Полярний'",
    price: 199.99,
    description: "Ідеальне поєднання стилю та функціональності для захисту від найлютіших морозів. Короткий крій і об'ємні пухові секції (дутий дизайн) забезпечують максимальне тепло.",
    category: "men's clothing",
    image: "https://i.pinimg.com/1200x/e2/25/f4/e225f4f3aed044018775a1a22afb9420.jpg",
    rating: { rate: 4.8, count: 29 },
    size: "L",
    color: "Білий",
    inStock: true,
    brand: "LINO",
    material: "Нейлон, пух"
  },
  {
    id: 11,
    title: "Куртка 'Байкер-Бомбер'",
    price: 149.99,
    description: "Сучасне поєднання класичного силуету бомбера з брутальністю шкіряної куртки. Виготовлена з якісної екошкіри або натуральної шкіри з благородним матовим блиском.",
    category: "men's clothing",
    image: "https://i.pinimg.com/1200x/15/19/f4/1519f48479a686af7f71400d703063a5.jpg",
    rating: { rate: 4.6, count: 41 },
    size: "M",
    color: "Чорний",
    inStock: false,
    brand: "LINO",
    material: "Екошкіра"
  },
  {
    id: 12,
    title: "Штани 'Скандинавія'",
    price: 59.99,
    description: "Ультракомфортна модель для повсякденного носіння, виконана у модному кольорі 'еспресо з молоком'. Широкий прямий крій (Wide Leg) та щільна трикотажна тканина створюють розслаблений і стильний силует.",
    category: "men's clothing",
    image: "https://i.pinimg.com/736x/3c/49/ed/3c49ed2d0b6f1037e8e278e1fb077983.jpg",
    rating: { rate: 4.4, count: 36 },
    size: "L",
    color: "Бежевий",
    inStock: true,
    brand: "LINO",
    material: "Трикотаж бавовняний"
  }
];
